[variables]
NODE_VERSION = "20"

[phases.setup]
nixPkgs = ["php82", "composer", "nodejs"]

[phases.install]
cmds = [
  "rm -rf node_modules package-lock.json",
  "composer install --no-scripts --no-interaction",
  "npm install"
]

[phases.build]
cmds = [
  "npm run build"
]

[start]
cmd = "php artisan migrate --force && php artisan storage:link && php artisan config:cache && php artisan route:cache && php artisan view:cache && php artisan serve --host=0.0.0.0 --port=$PORT"
